FROM registry.access.redhat.com/ubi9-minimal:9.3-1552

RUN microdnf install -y python3 python3-pip gcc g++ shadow-utils && microdnf clean all
RUN useradd -r -g root -m -d /home/default -s /bin/bash default
WORKDIR /home/default
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir --upgrade -r requirements.txt
USER default
COPY run.sh run.sh
EXPOSE 8001
ENTRYPOINT [ "sh", "run.sh" ]
