#
# Copyright (C) 2024 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

# Stage 1: Build dependencies
FROM registry.access.redhat.com/ubi9/python-311:1-72.1722518949 AS builder
USER 0
RUN dnf install -y python3-dnf-plugin-versionlock && \
    dnf install -y mesa-vulkan-drivers-23.3.3-1.el9.x86_64 && \
    dnf versionlock mesa-vulkan-drivers-23.3.3-1.el9.x86_64 && \
    dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
    dnf install -y git cmake ninja-build gcc gcc-c++ && \
    dnf copr enable -y ligenix/enterprise-sandbox epel-9-x86_64 && \
    dnf install -y vulkan-headers vulkan-tools && \
    dnf clean all

WORKDIR /locallm
COPY requirements.txt ./
RUN pip install --upgrade pip
ENV CMAKE_ARGS="-DLLAMA_VULKAN=on"
ENV FORCE_CMAKE=1
RUN pip install --target=/locallm --no-cache-dir --upgrade -r requirements.txt

# Stage 2: Create final image with minimal content
FROM registry.access.redhat.com/ubi9/python-311:1-72.1722518949
COPY --from=builder /locallm/ /locallm
COPY --from=builder /usr/bin/vkcube* /usr/bin/
COPY --from=builder /usr/bin/vulkaninfo /usr/bin/vulkaninfo
COPY --from=builder /usr/lib/ /usr/lib/
COPY --from=builder /usr/lib64/ /usr/lib64/
COPY --from=builder /usr/share/vulkan /usr/share/vulkan
COPY --from=builder /usr/include/vulkan /usr/include/vulkan
COPY --from=builder /etc/ /etc/
USER 1001
WORKDIR /locallm
COPY requirements.txt ./
COPY run.sh ./
ENTRYPOINT [ "sh", "run.sh" ]
