#
# Copyright (C) 2024 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

FROM registry.access.redhat.com/ubi9-minimal:9.5-1741850109

RUN microdnf install -y python3 python3-pip gcc g++ shadow-utils && microdnf clean all
RUN useradd -r -g root -m -d /home/default -s /bin/bash default
WORKDIR /home/default
COPY requirements.txt requirements.txt
COPY llama-cpp-python llama-cpp-python
RUN pip install --no-cache-dir --upgrade -r requirements.txt
USER default
COPY run.sh run.sh
EXPOSE 8000
ENTRYPOINT [ "sh", "run.sh" ]
